version: "3.9"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: product-service
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql    
    networks:
      springboot-mysql-net:

  product-service:
    image: product-service:v.01
    container_name: product-service
    build: .
    ports:
      - 8082:8082
    depends_on:
      - mysqldb
    environment:  
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/product-service
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:
