version: "3.9"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:2017"

  order-service:
    image: order-service:v.01
    container_name: order-service
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    restart: on-failure

